FROM arm32v7/alpine:latest

RUN apk add --no-cache curl

RUN curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz | tar zxvf - -C . && mv qemu-3.0.0+resin-arm/qemu-arm-static .

ENTRYPOINT ["/usr/bin/curl"]
