FROM alpine:3.10

RUN curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-aarch64.tar.gz | tar zxvf - -C . && mv qemu-3.0.0+resin-aarch64/qemu-arm-static .
RUN apk add --no-cache curl

ENTRYPOINT ["/usr/bin/curl"]
